name: Update Movies
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: {python-version: '3.9'}
      - run: pip install requests
      - run: python fetch_movies.py
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      - run: |
          git config --global user.name "bot"
          git config --global user.email "bot@bot.com"
          git add movies.json
          git commit -m "Auto Update"
          git push
