name: Update Movies
on:
  schedule:
    - cron: '0 0 * * *' # Ye har 24 ghante mein chalega
  workflow_dispatch: # Isse tum button daba kar manually bhi chala sakte ho

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install requirements
        run: pip install requests
      - name: Run Script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python fetch_movies.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add movies.json
          git commit -m "Update movies list" -a || echo "No changes to commit"
          git push
          
